# This file maps each exam_type to a specific report generation strategy.
# The ReportCoordinator reads this configuration to determine which logic to apply.

strategies:
  ionnutri:
    type: multistage
  vidanova:
    type: onestage
