apiVersion: apps/v1
kind: Deployment
metadata:
  name: ion-nutri-staging-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ion-nutri-staging-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ion-nutri-staging-api
    spec:
      containers:
        - name: api
          image: 716814888065.dkr.ecr.us-east-2.amazonaws.com/ion-nutri:backend-latest-staging
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: NEO4J_URI
              value: bolt://localhost:7687
            - name: NEO4J_USER
              value: neo4j
            - name: NEO4J_PASSWORD
              value: password
            - name: MLFLOW_ENABLED
              value: "false"
            - name: OPENROUTER_API_KEY
              value: ""
            - name: OPENROUTER_API_BASE
              value: https://openrouter.ai/api/v1
            - name: OPENROUTER_MODEL
              value: google/gemini-2.5-flash-preview
            - name: OPENROUTER_MAX_TOKENS
              value: "4096"
            - name: OPENROUTER_TEMPERATURE
              value: "1"
          # resources:
          #   limits:
          #     memory: "512Mi"
          #     cpu: "500m"
          #   requests:
          #     memory: "256Mi"
          #     cpu: "100m"

        - name: neo4j
          image: neo4j:5.26-community
          imagePullPolicy: Always
          ports:
            - containerPort: 7474 #http
            - containerPort: 7687 #bolt
---
apiVersion: v1
kind: Service
metadata:
  name: ion-nutri-staging-api
  namespace: default
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ion-nutri-staging-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ion-nutri-staging-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ion-nutri-staging-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ion-nutri-staging-frontend
    spec:
      containers:
        - name: frontend
          image: 716814888065.dkr.ecr.us-east-2.amazonaws.com/ion-nutri:frontend-latest-staging
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          # resources:
          #   limits:
          #     memory: "256Mi"
          #     cpu: "250m"
          #   requests:
          #     memory: "128Mi"
          #     cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: ion-nutri-staging-frontend
  namespace: default
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ion-nutri-staging-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
